/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InteriorDesignerTirunelveliRouteImport } from './routes/interior-designer-tirunelveli'
import { Route as InteriorDesignerPalayamkottaiRouteImport } from './routes/interior-designer-palayamkottai'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWardrobeDesignRouteImport } from './routes/services/wardrobe-design'
import { Route as ServicesModularKitchenRouteImport } from './routes/services/modular-kitchen'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorDesignerTirunelveliRoute =
  InteriorDesignerTirunelveliRouteImport.update({
    id: '/interior-designer-tirunelveli',
    path: '/interior-designer-tirunelveli',
    getParentRoute: () => rootRouteImport,
  } as any)
const InteriorDesignerPalayamkottaiRoute =
  InteriorDesignerPalayamkottaiRouteImport.update({
    id: '/interior-designer-palayamkottai',
    path: '/interior-designer-palayamkottai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWardrobeDesignRoute = ServicesWardrobeDesignRouteImport.update({
  id: '/wardrobe-design',
  path: '/wardrobe-design',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesModularKitchenRoute = ServicesModularKitchenRouteImport.update({
  id: '/modular-kitchen',
  path: '/modular-kitchen',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/interior-designer-palayamkottai': typeof InteriorDesignerPalayamkottaiRoute
  '/interior-designer-tirunelveli': typeof InteriorDesignerTirunelveliRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/modular-kitchen': typeof ServicesModularKitchenRoute
  '/services/wardrobe-design': typeof ServicesWardrobeDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/interior-designer-palayamkottai': typeof InteriorDesignerPalayamkottaiRoute
  '/interior-designer-tirunelveli': typeof InteriorDesignerTirunelveliRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/modular-kitchen': typeof ServicesModularKitchenRoute
  '/services/wardrobe-design': typeof ServicesWardrobeDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/interior-designer-palayamkottai': typeof InteriorDesignerPalayamkottaiRoute
  '/interior-designer-tirunelveli': typeof InteriorDesignerTirunelveliRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/modular-kitchen': typeof ServicesModularKitchenRoute
  '/services/wardrobe-design': typeof ServicesWardrobeDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/interior-designer-palayamkottai'
    | '/interior-designer-tirunelveli'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/services/modular-kitchen'
    | '/services/wardrobe-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/interior-designer-palayamkottai'
    | '/interior-designer-tirunelveli'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/services/modular-kitchen'
    | '/services/wardrobe-design'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/interior-designer-palayamkottai'
    | '/interior-designer-tirunelveli'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/services/modular-kitchen'
    | '/services/wardrobe-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InteriorDesignerPalayamkottaiRoute: typeof InteriorDesignerPalayamkottaiRoute
  InteriorDesignerTirunelveliRoute: typeof InteriorDesignerTirunelveliRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-designer-tirunelveli': {
      id: '/interior-designer-tirunelveli'
      path: '/interior-designer-tirunelveli'
      fullPath: '/interior-designer-tirunelveli'
      preLoaderRoute: typeof InteriorDesignerTirunelveliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-designer-palayamkottai': {
      id: '/interior-designer-palayamkottai'
      path: '/interior-designer-palayamkottai'
      fullPath: '/interior-designer-palayamkottai'
      preLoaderRoute: typeof InteriorDesignerPalayamkottaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/wardrobe-design': {
      id: '/services/wardrobe-design'
      path: '/wardrobe-design'
      fullPath: '/services/wardrobe-design'
      preLoaderRoute: typeof ServicesWardrobeDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/modular-kitchen': {
      id: '/services/modular-kitchen'
      path: '/modular-kitchen'
      fullPath: '/services/modular-kitchen'
      preLoaderRoute: typeof ServicesModularKitchenRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesModularKitchenRoute: typeof ServicesModularKitchenRoute
  ServicesWardrobeDesignRoute: typeof ServicesWardrobeDesignRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesModularKitchenRoute: ServicesModularKitchenRoute,
  ServicesWardrobeDesignRoute: ServicesWardrobeDesignRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InteriorDesignerPalayamkottaiRoute: InteriorDesignerPalayamkottaiRoute,
  InteriorDesignerTirunelveliRoute: InteriorDesignerTirunelveliRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
